#!/bin/bash
env_reference_process=$(pgrep -u $USER xfce4-session || pgrep -u $USER ciannamon-session || pgrep -u $USER gnome-session || pgrep -u $USER gnome-shell || pgrep -u $USER kdeinit)
export DBUS_SESSION_BUS_ADDRESS=$(cat /proc/"$env_reference_process"/environ | grep -z ^DBUS_SESSION_BUS_ADDRESS= | sed s/DBUS_SESSION_BUS_ADDRESS=//)
export DISPLAY=$(cat /proc/"$env_reference_process"/environ | grep -z ^DISPLAY= | sed s/DISPLAY=//)

function btt() {
	while (( $# > 0 )); do
		((x++))
		if (( x % 42 == 0 )); then
			printf "\x$(echo obase=16\;ibase=2\;$1 | bc)\-\n"
		else
			printf "\x$(echo obase=16\;ibase=2\;$1 | bc)"
		fi
		shift
	done
}

function check_args() {
	if (( $# == 1 )); then
		outwords="$(btt $(echo $1 | fold -w8))"
	else
		outwords="$(btt $@)"
	fi
}

check_args $(xsel -o)
wait_time=$(( "$(echo "${outwords}" | wc -w)" / 2 * 1000 ))
notify-send -t $wait_time "Converted words: " "${outwords}"
