#!/bin/bash
set_display_preferences
function btt() {
	while (( $# > 0 )); do
		((x++))
		if (( x % 42 == 0 )); then
			printf "\x$(echo obase=16\;ibase=2\;$1 | bc)\-\n"
		else
			printf "\x$(echo obase=16\;ibase=2\;$1 | bc)"
		fi
		shift
	done
}

function check_args() {
	if (( $# == 1 )); then
		outwords="$(btt $(echo $1 | fold -w8))"
	else
		outwords="$(btt $@)"
	fi
}

check_args $(xsel -o)
wait_time=$(( "$(echo "${outwords}" | wc -w)" / 2 * 1000 ))
notify-send -t $wait_time "Converted words: " "${outwords}"
